---
title: "Realized Higher Moment Measures"
description: |
  Exploring Realized Higher Moment Measures on the S&P/BMV IPC Index
author:
  - name: Alexis Solis Cancino
    affiliation: ITAM
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    css: "resources/theme.css"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  
  # Places figures on their own pages
  fig.pos = 'p',
  
  # Figure resolution and size
  out.width = '100%',
  dpi = 400,
  
  # Latex figure environment
  fig.env = "figure"
)


# --- Load the libraries! ---

# Data Wrangling
library(tidyverse)
library(lubridate)
library(skimr)
library(glue)

# Time Series
library(timetk)
library(tidyquant)
# library(hms)
# library(modeltime)
# library(tidymodels)

# Visualization
# library(ggthemes)
library(scales)
# library(ghibli)
library(cowplot)
# library(plotly)
library(gt)
library(progress)

# Reproducibility
library(usethis)
library(here)


# Speed
# library(data.table)
# library(dtplyr)
library(arrow)
library(furrr)


# Setup parallelization plan
future::plan(strategy = multiprocess, workers = 11)

# --- Setup the ggplot theme ---
source("resources/ggplot2_themes.R")
```

```{r}
# Read the data
ipc_intraday <- read_parquet(here("data-processed/intraday_ipc.parquet"))
```

# Realized Volatility
